name: Release

on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: 'Tag (semantic version)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0
      - name: Create Release Notes
        if: ${{ !startsWith(github.ref, 'refs/tags/') && !contains(github.event.inputs.versionTag, "alpha") }}
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.event.inputs.versionTag }}",
              generate_release_notes: true
            });
      - name: Create Pre-Release Notes
        if: ${{ !startsWith(github.ref, 'refs/tags/') && contains(github.event.inputs.versionTag, "alpha") }}
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.event.inputs.versionTag }}",
              generate_release_notes: true
            });
